FROM mariadb:{{mariadbVersion}}
{{#if authorName}}LABEL maintainer="{{authorName}}{{#if authorEmail}} <{{authorEmail}}>{{/if}}"{{/if}}

# Mount this volume to help loading/exporting dumps
RUN mkdir /workdir
VOLUME /workdir

RUN usermod -u ${USER_ID:-1000} mysql && groupmod -g ${GROUP_ID:-1000} mysql
