#!/usr/bin/env sh
. "$DOCKER_DEVBOX_DIR/.bash_enter.d/03-functions"

run --user www-data --entrypoint php --workdir="$(_docker_devbox_map_workdir "/app")" {{service.name}} /composer/vendor/phing/phing/bin/phing "$@"
