FROM php:{{phpVersion}}-cli
{{#if authorName}}LABEL maintainer="{{authorName}}{{#if authorEmail}} <{{authorEmail}}>{{/if}}"{{/if}}
\{{#DOCKER_DEVBOX_COPY_CA_CERTIFICATES}}

COPY .ca-certificates/* /usr/local/share/ca-certificates/
RUN update-ca-certificates
\{{/DOCKER_DEVBOX_COPY_CA_CERTIFICATES}}

ENV COMPOSER_HOME /composer
ENV PATH /composer/vendor/bin:$PATH
ENV COMPOSER_ALLOW_SUPERUSER 1

RUN curl -fsSL -o /tmp/composer-setup.php https://getcomposer.org/installer \
&& curl -fsSL -o /tmp/composer-setup.sig https://composer.github.io/installer.sig \
&& php -r "if (hash('SHA384', file_get_contents('/tmp/composer-setup.php')) !== trim(file_get_contents('/tmp/composer-setup.sig'))) { unlink('/tmp/composer-setup.php'); echo 'Invalid installer' . PHP_EOL; exit(1); }" \
&& php /tmp/composer-setup.php --no-ansi --install-dir=/usr/local/bin --filename=composer --snapshot && rm -rf /tmp/composer-setup.php \
&& apt-get update -y && apt-get install -y git zip unzip && rm -rf /var/lib/apt/lists/* \
&& composer global require hirak/prestissimo

{{#semver phpVersion '<7'}}
RUN echo "date.timezone=${PHP_TIMEZONE:-UTC}" > $PHP_INI_DIR/conf.d/composer.ini \
&& echo "always_populate_raw_post_data=-1" > $PHP_INI_DIR/conf.d/composer.ini
{{/semver}}

# Install phing
RUN composer global require phing/phing pear/archive_tar --prefer-dist --no-progress --no-suggest \
&& chmod +x ${COMPOSER_HOME}/vendor/phing/phing/bin/phing && chown ${USER_ID:-1000}:${GROUP_ID:-1000} ${COMPOSER_HOME}/vendor/phing/phing/bin/phing

# Docker CLI
ARG DOCKER_VERSION=18.03.1-ce
ARG DOCKER_COMPOSE_VERSION=1.21.2
RUN curl -fsSL -o docker.tgz https://download.docker.com/linux/static/stable/x86_64/docker-${DOCKER_VERSION}.tgz \
&& tar xzvf docker.tgz \
&& cp docker/* /usr/bin/ \
&& chmod +x /usr/bin/docker \
&& curl -fsSL https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` -o /usr/bin/docker-compose \
&& chmod +x /usr/bin/docker-compose

RUN groupadd -g 998 docker
RUN usermod -a -G docker www-data

RUN usermod -u ${USER_ID:-1000} www-data
RUN groupmod -g ${GROUP_ID:-1000} www-data
RUN chown -R ${USER_ID:-1000}:${GROUP_ID:-1000} $COMPOSER_HOME

ENTRYPOINT "/composer/vendor/phing/phing/bin/phing"
