FROM djfarrelly/maildev
{{#if authorName}}LABEL maintainer="{{authorName}}{{#if authorEmail}} <{{authorEmail}}>{{/if}}"{{/if}}

COPY .ca-certificates/* /usr/local/share/ca-certificates/
RUN apk add --update ca-certificates && update-ca-certificates
