FROM node:{{nodeVersion}}
{{#if authorName}}LABEL maintainer="{{authorName}}{{#if authorEmail}} <{{authorEmail}}>{{/if}}"{{/if}}
\{{#DOCKER_DEVBOX_COPY_CA_CERTIFICATES}}

COPY .ca-certificates/* /usr/local/share/ca-certificates/
RUN update-ca-certificates
ENV NODE_EXTRA_CA_CERTS=/etc/ssl/certs/ca-certificates.crt
\{{/DOCKER_DEVBOX_COPY_CA_CERTIFICATES}}

# Mise à jour de npm
RUN npm i --global npm

{{> fixuid}}

WORKDIR /app

USER node

RUN yarn config set cafile ${NODE_EXTRA_CA_CERTS} --global
RUN npm config set prefix /home/node/.npm-packages
ENV PATH="${PATH}:/home/node/.npm-packages/bin"

{{#inArray nodeTools "@vue/cli"}}

RUN npm install -g @vue/cli
{{/inArray}}
{{#inArray nodeTools "@angular/cli"}}

RUN npm install -g @angular/cli
{{/inArray}}
{{#inArray nodeTools "create-react-app"}}

RUN npm install -g create-react-app
{{/inArray}}
{{#inArray nodeTools "node-sass"}}

RUN npm install -g node-sass chokidar-cli compass-importer
{{/inArray}}

VOLUME /app
VOLUME /home/node/.cache
