FROM node:{{nodeVersion}}
{{#if authorName}}LABEL maintainer="{{authorName}}{{#if authorEmail}} <{{authorEmail}}>{{/if}}"{{/if}}

COPY .ca-certificates/* /usr/local/share/ca-certificates/
RUN update-ca-certificates

ENV NODE_EXTRA_CA_CERTS=/etc/ssl/certs/ca-certificates.crt

# Mise à jour de npm
RUN npm i --global npm

# Allow nodeJS to run server on port < 1024
RUN apt-get update -y && apt-get install -y libcap2-bin && rm -rf /var/lib/apt/lists/* \
&& setcap 'cap_net_bind_service=+ep' $(which node)

RUN usermod -u ${USER_ID:-1000} node && groupmod -g ${GROUP_ID:-1000} node \
&& mkdir /home/node/.npm-packages && chown -R ${USER_ID:-1000}:${GROUP_ID:-1000} /home/node/.npm-packages \
&& mkdir -p /home/node/.cache/yarn && chown -R ${USER_ID:-1000}:${GROUP_ID:-1000} /home/node/.cache \
&& mkdir /app && chown -R ${USER_ID:-1000}:${GROUP_ID:-1000} /app

WORKDIR /app

USER node

RUN yarn config set cafile ${NODE_EXTRA_CA_CERTS} --global
RUN npm config set prefix /home/node/.npm-packages
ENV PATH="${PATH}:/home/node/.npm-packages/bin"

{{#inArray nodeTools "@vue/cli"}}

RUN npm install -g @vue/cli
{{/inArray}}
{{#inArray nodeTools "@angular/cli"}}

RUN npm install -g @angular/cli
{{/inArray}}
{{#inArray nodeTools "create-react-app"}}

RUN npm install -g create-react-app
{{/inArray}}
{{#inArray nodeTools "node-sass"}}

RUN npm install -g node-sass chokidar-cli compass-importer
{{/inArray}}

VOLUME /app
VOLUME /home/node/.cache
