#!/usr/bin/env bash

if [ -f "$DOCKER_DEVBOX_DIR/.bash_leave.d/95-cleanup-variables" ]; then
  . "$DOCKER_DEVBOX_DIR/.bash_leave.d/95-cleanup-variables"
fi

BASH_ENTER_ENV_USER_FILE=~/.docker-devbox/.bash_enter.env
[ -f "$BASH_ENTER_ENV_USER_FILE" ] && . "$BASH_ENTER_ENV_USER_FILE"

BASH_ENTER_ENV_FILE="$DOCKER_DEVBOX_DIR/.bash_enter.env"
cp -n "$BASH_ENTER_ENV_FILE.dist" "$BASH_ENTER_ENV_FILE"
[ -f "$BASH_ENTER_ENV_FILE" ] && . "$BASH_ENTER_ENV_FILE"
