#!/usr/bin/env sh
# shellcheck disable=SC2034

USER_ID=$(id -u)
GROUP_ID=$(id -g)
USER_NAME=$(id -un)
GROUP_NAME=$(id -gn)
DOCKER_DEVBOX_IP=$(ip addr show dev docker0 | grep -o "inet [0-9]*\.[0-9]*\.[0-9]*\.[0-9]*" | grep -o "[0-9]*\.[0-9]*\.[0-9]*\.[0-9]*")
HOST_IP=${HOST_IP-${DOCKER_DEVBOX_IP}}

autostash USER_ID
autostash GROUP_ID
autostash USER_NAME
autostash GROUP_NAME
autostash HOST_IP

# shellcheck disable=SC2153
autostash COMPOSE_PROJECT_DIR="$DOCKER_DEVBOX_DIR"

if [ -z ${COMPOSE_PROJECT_NAME+x} ]; then
    # If COMPOSE_PROJECT_NAME is not defined, build it from directory name.
    name=$(basename "${COMPOSE_PROJECT_DIR}")
    COMPOSE_PROJECT_NAME=$(echo "$name" | sed -r "s/[ _.-]//g" | sed -r "s/.*/\L\0/g")
fi

if [ -z ${COMPOSE_NETWORK_NAME+x} ]; then
    # If COMPOSE_NETWORK_NAME is not defined, build it from project name.
    COMPOSE_NETWORK_NAME="$COMPOSE_PROJECT_NAME""_default"
fi

autostash COMPOSE_PROJECT_NAME
autostash COMPOSE_NETWORK_NAME

DOCKER_VERSION=$(docker --version | sed -rn "s/Docker version (.*?), build .*/\1/p")
DOCKER_COMPOSE_VERSION=$(docker-compose --version | sed -rn "s/docker-compose version (.*?), build .*/\1/p")

autostash DOCKER_VERSION
autostash DOCKER_COMPOSE_VERSION

# Define DOCKER_DEVBOX_ENV to customize environment configuration files
autostash DOCKER_DEVBOX_ENV="${DOCKER_DEVBOX_ENV:-dev}"
autostash DOCKER_DEVBOX_ENV_LIST="${DOCKER_DEVBOX_ENV_LIST:-prod stage dev}" # Supported environments (symlinks)
