#!/usr/bin/env bash

if [[ -n "${DOCKER_DEVBOX_CFSSL_ENABLED}" && "${DOCKER_DEVBOX_CFSSL_ENABLED}" != "false" ]]; then
  CFSSL_CLI=$(command -v cfssl-cli)

  if [ ! -x "$CFSSL_CLI" ]; then
     echo "$(tput setaf 3)cfssl-cli is not available. Downloading binary ...$(tput sgr0)"
     CFSSL_CLI_VERSION=$(curl -s https://api.github.com/repos/Toilal/python-cfssl-cli/releases/latest | grep 'tag_name' | cut -d\" -f4)

     curl -fsSL -o "$DOCKER_DEVBOX_DIR/.bin/cfssl-cli" "https://github.com/Toilal/python-cfssl-cli/releases/download/$CFSSL_CLI_VERSION/cfssl-cli"
     chmod +x "$DOCKER_DEVBOX_DIR/.bin/cfssl-cli"
  fi
fi

