#!/usr/bin/env bash

if [[ -n "${DOCKER_DEVBOX_SSL}" && "${DOCKER_DEVBOX_SSL}" == "mkcert" ]]; then
  MKCERT=$(command -v mkcert)

  if [ ! -x "$MKCERT" ]; then
     echo "$(tput setaf 3)mkcert is not available. Downloading binary ...$(tput sgr0)"
     MKCERT_VERSION=$(curl -s https://api.github.com/repos/FiloSottile/mkcert/releases/latest | grep 'tag_name' | cut -d\" -f4)

     curl -fsSL -o "$DOCKER_DEVBOX_DIR/.bin/mkcert" "https://github.com/FiloSottile/mkcert/releases/download/$MKCERT_VERSION/mkcert-$MKCERT_VERSION-linux-amd64"
     chmod +x "$DOCKER_DEVBOX_DIR/.bin/mkcert"

     echo "$(tput setaf 3)You should now run \"sudo mkcert -install\" manually. $(tput sgr0)"
  fi
fi

