#!/usr/bin/env bash

RECURSIVE_MARKER="\[\*\]"

if [ -n "${DOCKER_DEVBOX_MO_DIRS}" ]; then
  for TEMPLATE_DIR in $DOCKER_DEVBOX_MO_DIRS; do
    maxdepth=" -maxdepth 1"

    HAS_RECURSIVE_MARKER=$(echo "$TEMPLATE_DIR" | sed -n "/$RECURSIVE_MARKER$/ p")
    if [ -n "$HAS_RECURSIVE_MARKER" ]; then
      # shellcheck disable=SC2001
      TEMPLATE_DIR=$(echo "$TEMPLATE_DIR" | sed "s/$RECURSIVE_MARKER$//g")
      maxdepth=""
    fi

    if [ -d "$TEMPLATE_DIR" ]; then
      TEMPLATES=$(find "$TEMPLATE_DIR"$maxdepth -type f -name '*.mo' -o -name '*.mo.*')
      for template in $TEMPLATES; do
        target=$(echo "$template" | sed -re 's/(.*).mo((.|$).*)/\1\2/g')
        mo <"$template"> "$target"
        echo "$(tput setaf 2)$(_utils_relative_path "$template") -> $(basename "$target")$(tput sgr0)"
      done
    fi
  done
fi
