#!/usr/bin/env bash

CA_CERTIFICATES_DIR="$DOCKER_DEVBOX_DIR/.docker/.ca-certificates"
FILE_COUNT=0

if [ -n "$DOCKER_DEVBOX_CA_CERTIFICATES" ]; then
  rm -Rf "/${CA_CERTIFICATES_DIR:?}"
  mkdir -p "/${CA_CERTIFICATES_DIR:?}"

  rm -f "$CA_CERTIFICATES_DIR/.empty"

  for CERT in $DOCKER_DEVBOX_CA_CERTIFICATES; do
    cp -L "$CERT" "$CA_CERTIFICATES_DIR"
  done

  for pem in "$CA_CERTIFICATES_DIR"/*.pem; do
    mv "$pem" "$CA_CERTIFICATES_DIR/$(basename "$pem" .pem).crt"
  done

  if [ -n "$(ls -A "$CA_CERTIFICATES_DIR")" ]; then
    for cert in "$CA_CERTIFICATES_DIR"/*; do
      echo "$(tput setaf 2)$(basename "$cert")$(tput sgr0)"
      FILE_COUNT=$((FILE_COUNT+1))
    done
  fi

  if [ "$FILE_COUNT" -eq "0" ]; then
    echo "$(tput setaf 3)No certificates found at ${DOCKER_DEVBOX_CA_CERTIFICATES}$(tput sgr0)"
    echo "$(tput setaf 3)Creating .empty file$(tput sgr0)"
    touch "$CA_CERTIFICATES_DIR/.empty"
  fi
fi
