#!/usr/bin/env bash

if [[ -n "${DOCKER_DEVBOX_CFSSL_ENABLED}" && "${DOCKER_DEVBOX_CFSSL_ENABLED}" != "false" ]]; then
  CFSSL_CLI_EXE=$(command -v cfssl-cli)
  CONFIG="$DOCKER_DEVBOX_DIR/.cfssl-cli/config.yml"
  DESTINATION="$DOCKER_DEVBOX_DIR/.nginx-proxy/certs"

  CONFIG_OPTION=""
  if [ -f "$CONFIG" ]; then
    CONFIG_OPTION="--config ""$CONFIG"
  fi

  if [ -f "$CFSSL_CLI_EXE" ]; then
     for DOMAIN in $(dc config | sed -n -e 's/\s*VIRTUAL_HOST: //p'); do
        DESTINATION_CRT="$DESTINATION/${DOMAIN}.crt"
        DESTINATION_KEY="$DESTINATION/${DOMAIN}.key"

        if [ ! -f "$DESTINATION_CRT" ] || [ ! -f "$DESTINATION_KEY" ]; then
            mkdir -p "$DESTINATION"

            echo "$(tput setaf 3)Generating SSL certificate for ${DOMAIN} with cfssl-cli$(tput sgr0)"
            # shellcheck disable=SC2086
            cfssl-cli gencert ${CONFIG_OPTION} --destination "$DESTINATION" "${DOMAIN}"
            echo "$(tput setaf 2)SSL certificate has been generated for ${DOMAIN}$(tput sgr0)"
        fi
     done
  fi
fi
