#!/usr/bin/env bash

if [[ -n "${DOCKER_DEVBOX_SSL}" && "${DOCKER_DEVBOX_SSL}" == "mkcert" ]]; then
  MKCERT_EXE=$(command -v mkcert)
  DESTINATION="$DOCKER_DEVBOX_DIR/.certs"

  if [ -f "$MKCERT_EXE" ]; then
     for RAWDOMAIN in $(dc config | sed -n -e 's/\s*VIRTUAL_HOST: //p'); do
        echo "$RAWDOMAIN" | tr ',' '\n' | while read -r DOMAIN; do
          DESTINATION_CRT="$DESTINATION/${DOMAIN}.crt"
          DESTINATION_KEY="$DESTINATION/${DOMAIN}.key"

          if [ ! -f "$DESTINATION_CRT" ] || [ ! -f "$DESTINATION_KEY" ]; then
            mkdir -p "$DESTINATION"

            echo "$(tput setaf 3)Generating SSL certificate for ${DOMAIN} with mkcert$(tput sgr0)"
            # shellcheck disable=SC2086
            if mkcert -cert-file "$DESTINATION_CRT" -key-file "$DESTINATION_KEY" "${DOMAIN}"; then
              echo "$(tput setaf 2)SSL certificate has been generated for ${DOMAIN}$(tput sgr0)"
            else
              echo "$(tput setaf 1)SSL certificate generation has failed for ${DOMAIN}$(tput sgr0)"
            fi
          fi
        done
     done
  fi
fi
