#!/usr/bin/env bash

SHOULD_RESTART_CONTAINER=0

PROJECT_NGINX_PROXY_PATH="$DOCKER_DEVBOX_DIR/.nginx-proxy"
USER_NGINX_PROXY_PATH="$HOME/.nginx-proxy"

_cp_file_if_different() {
SRC="$1"
DEST="$2"

if [ -f "$SRC" ] && [ ! -f "$DEST" ]; then
  cp -f "$SRC" "$DEST"
  return 0
else
  if [ ! -f "$SRC" ] && [ -f "$DEST" ]; then
    rm "$DEST"
    return 0
  else
    if [ -f "$SRC" ] && [ -f "$DEST" ] && ! cmp -s "$SRC" "$DEST"; then
      cp -f "$SRC" "$DEST"
      return 0
    fi
  fi
fi

return 1
}

for DOMAIN in $(dc config | sed -n -e 's/\s*VIRTUAL_HOST: //p'); do
  CERT_KEY="${PROJECT_NGINX_PROXY_PATH}/certs/${DOMAIN}.key"
  CERT_KEY_DEST="${USER_NGINX_PROXY_PATH}/certs/${DOMAIN}.key"

  CERT_CRT="${PROJECT_NGINX_PROXY_PATH}/certs/${DOMAIN}.crt"
  CERT_CRT_DEST="${USER_NGINX_PROXY_PATH}/certs/${DOMAIN}.crt"

  if _cp_file_if_different "$CERT_KEY" "$CERT_KEY_DEST"; then
    SHOULD_RESTART_CONTAINER=1
  fi

  if _cp_file_if_different "$CERT_CRT" "$CERT_CRT_DEST"; then
    SHOULD_RESTART_CONTAINER=1
  fi

  for VHOST_CONF in "$PROJECT_NGINX_PROXY_PATH"/vhost.d/*; do
    # shellcheck disable=SC2001
    VHOST_CONF_DEST_BASENAME=$(basename "$(echo "$VHOST_CONF" | sed -e 's/\[domain\]/'"${DOCKER_DEVBOX_DOMAIN_PREFIX}.${DOCKER_DEVBOX_DOMAIN}"'/g')")

    if [[ "$DOMAIN" == "$VHOST_CONF_DEST_BASENAME" ]]; then
      if _cp_file_if_different "$VHOST_CONF" "$USER_NGINX_PROXY_PATH/vhost.d/$VHOST_CONF_DEST_BASENAME"; then
        SHOULD_RESTART_CONTAINER=1
      fi
    fi

    if [[ "$DOMAIN""_location" == "$VHOST_CONF_DEST_BASENAME" ]]; then
      if _cp_file_if_different "$VHOST_CONF" "$USER_NGINX_PROXY_PATH/vhost.d/$VHOST_CONF_DEST_BASENAME"; then
        SHOULD_RESTART_CONTAINER=1
      fi
    fi
  done
done

if [ "$SHOULD_RESTART_CONTAINER" -eq "1" ]; then
  echo "$(tput setaf 3)nginx-proxy configuration has been applied. Restarting nginx-proxy container ...$(tput sgr0)"
  docker restart nginx-proxy
  echo "$(tput setaf 2)nginx-proxy container has been restarted."
fi
