#!/usr/bin/env bash

DOCKER_DIR="$DOCKER_DEVBOX_DIR/.docker"

if [ -d "$DOCKER_DIR" ]; then
  TEMPLATES=$(find $DOCKER_DIR -name '*.mo')
  for template in $TEMPLATES; do
    mo <"$template"> "${template%.*}"
  done
fi
