#!/usr/bin/env bash

if [ -f "./.init/init.sh" ] && [ -f ./.init/.should-initialize ]; then
  echo "Running initialization script: ./.init/init.sh"
  if ! ./.init/init.sh; then
    echo "Initialization failed"
  else
    echo "Initialization succeded"
  fi
fi
