FROM newtmitch/sonar-scanner:3.2.0-alpine
{{#if authorName}}LABEL maintainer="{{authorName}}{{#if authorEmail}} <{{authorEmail}}>{{/if}}"{{/if}}

COPY .ca-certificates/* /usr/local/share/ca-certificates/
RUN apk add --update ca-certificates && update-ca-certificates

ENTRYPOINT ["sonar-scanner", "-Dsonar.projectBaseDir=/root/src"]
CMD []
