#!/usr/bin/env sh

if [ -d "$DOCKER_DEVBOX_DIR"/.bash.lib.d ]; then
  for lib_script in "$DOCKER_DEVBOX_DIR"/.bash.lib.d/*; do
    # shellcheck source=/dev/null
    . "$lib_script"
  done
fi

OLD_PATH=PATH
unstash PATH

$@

stash PATH="$OLD_PATH"
