FROM mysql:{{mysqlVersion}}
{{#if authorName}}LABEL maintainer="{{authorName}}{{#if authorEmail}} <{{authorEmail}}>{{/if}}"{{/if}}

# Mount this volume to help loading/exporting dumps
RUN mkdir /workdir
VOLUME /workdir

{{> fixuid}}

USER mysql
