FROM alpine:3.6
MAINTAINER {{authorName}} <{{authorEmail}}>

\{{#if DOCKER_DEVBOX_CA_CERTIFICATES}}
COPY .ca-certificates/* /usr/local/share/ca-certificates/
RUN apk add --update ca-certificates
RUN update-ca-certificates
\{{/if}}

RUN apk add --update \
  ruby \
  ruby-dev \
  ruby-io-console \
  ruby-json \
  ruby-bigdecimal \
  bash \
  sqlite \
  sqlite-dev \
  openssl-dev \
  build-base

RUN gem install mailcatcher --no-rdoc --no-ri

# smtp port
EXPOSE 80 25

CMD ["mailcatcher", "-f", "--ip", "0.0.0.0", "--smtp-port", "25", "--http-port", "80"]
