FROM postgres:{{postgresVersion}}
{{#if authorName}}LABEL maintainer="{{authorName}}{{#if authorEmail}} <{{authorEmail}}>{{/if}}"{{/if}}

RUN apt-get update \
&& apt-get install -y --no-install-recommends postgresql \
&& rm -rf /var/lib/apt/lists/*

# Mount this volume to help loading/exporting dumps
RUN mkdir /workdir
VOLUME /workdir

# Fix permissions to match host user
RUN usermod -u ${USER_ID:-1000} postgres && groupmod -g ${GROUP_ID:-1000} postgres
